spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
    driverClassName: org.h2.Driver

  rabbitmq:
    addresses: amqps://uuxatqwn:uW9ZLL9SXRAeuseEAZwUEagzdwWfaR3o@gull.rmq.cloudamqp.com/uuxatqwn
    queue: ms-pedido

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties.hibernate.show_sql: true
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: create

  h2:
    console:
      enabled: true
      path: /h2
